version: '3.9'

services:
  rabbitmq:
    build: ./rabbitmq
    container_name: 'rabbitmq'
    restart: on-failure:5
    environment:
     - RABBITMQ_DEFAULT_USER=rtelecom_user
     - RABBITMQ_DEFAULT_PASS=rtelecom_password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    depends_on:
      - db
  servicedb:
    build:
      context: .
      dockerfile: ./servicedb/Dockerfile
    container_name: 'servicedb'
    command: python main.py
    restart: on-failure:5
    volumes:
      - ./servicedb:/servicedb
    environment:
      - DATABASE_URL=postgresql://rtelecom_user:rtelecom_password@db/citizen
    depends_on:
      - db
      - rabbitmq
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: python app.py
    restart: on-failure:5
    volumes:
      - ./backend:/backend
    ports:
      - 8888:8888
    depends_on:
      - servicedb
  db:
    image: postgres:15
    container_name: db
    restart: on-failure:5
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rtelecom_user
      - POSTGRES_PASSWORD=rtelecom_password
      - POSTGRES_DB=citizen
  frontend:
    restart: on-failure:5
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  db: